using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using CarScannerXamarinForms;
using CarScannerXamarinForms.Coding;
using CarScannerXamarinForms.Coding.Pages;
using CarScannerXamarinForms.Coding.PagesV2;
using CarScannerXamarinForms.Dashboard.DashboardGauges;
using CarScannerXamarinForms.DataRecorder;
using CarScannerXamarinForms.DTC;
using CarScannerXamarinForms.DTCv2;
using CarScannerXamarinForms.InApp;
using CarScannerXamarinForms.Pages;
using CarScannerXamarinForms.Pages.Dashboard;
using CarScannerXamarinForms.ProfilesV2;
using CarScannerXamarinForms.Settings;
using CarScannerXamarinForms.Settings.SettingsV3;
using CarScannerXamarinForms.Styles;
using CarScannerXamarinForms.UserControls;
using Xam.Plugin.SimpleColorPicker;
using Xamarin.Forms.Xaml;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: XamlCompilation(2)]
[assembly: NeutralResourcesLanguage("en")]
[assembly: XamlResourceId("CarScannerXamarinForms.App.xaml", "App.xaml", typeof(App))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.CodingA5CustomizationPage.xaml", "Coding/PagesV2/CodingA5CustomizationPage.xaml", typeof(CodingA5CustomizationPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.CodingListPageV2.xaml", "Coding/PagesV2/CodingListPageV2.xaml", typeof(CodingListPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.CodingModeSelectionV2.xaml", "Coding/PagesV2/CodingModeSelectionV2.xaml", typeof(CodingModeSelectionV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.CodingWithInputDetailsPageV2.xaml", "Coding/PagesV2/CodingWithInputDetailsPageV2.xaml", typeof(CodingWithInputDetailsPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.CodingWithOptionsDetailsPageV2.xaml", "Coding/PagesV2/CodingWithOptionsDetailsPageV2.xaml", typeof(CodingWithOptionsDetailsPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.PagesV2.UniversalCodingPageV2.xaml", "Coding/PagesV2/UniversalCodingPageV2.xaml", typeof(UniversalCodingPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingBackupPage.xaml", "Coding/Pages/CodingBackupPage.xaml", typeof(CodingBackupPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingLightConfigurationPage.xaml", "Coding/Pages/CodingLightConfigurationPage.xaml", typeof(CodingLightConfigurationPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingListPage.xaml", "Coding/Pages/CodingListPage.xaml", typeof(CodingListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingServiceProcedurePage.xaml", "Coding/Pages/CodingServiceProcedurePage.xaml", typeof(CodingServiceProcedurePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingWithColorSelectionPage.xaml", "Coding/Pages/CodingWithColorSelectionPage.xaml", typeof(CodingWithColorSelectionPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingWithHexInput.xaml", "Coding/Pages/CodingWithHexInput.xaml", typeof(CodingWithHexInput))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingWithInputDetailsPage.xaml", "Coding/Pages/CodingWithInputDetailsPage.xaml", typeof(CodingWithInputDetailsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingWithOptionsDetailsPage.xaml", "Coding/Pages/CodingWithOptionsDetailsPage.xaml", typeof(CodingWithOptionsDetailsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingWithTextInput.xaml", "Coding/Pages/CodingWithTextInput.xaml", typeof(CodingWithTextInput))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.DataSetDumperPage.xaml", "Coding/Pages/DataSetDumperPage.xaml", typeof(DataSetDumperPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.FPAProfileCodingPage.xaml", "Coding/Pages/FPAProfileCodingPage.xaml", typeof(FPAProfileCodingPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.FPAProfileEditor.xaml", "Coding/Pages/FPAProfileEditor.xaml", typeof(FPAProfileEditor))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.LongCodingPage.xaml", "Coding/Pages/LongCodingPage.xaml", typeof(LongCodingPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.MQBFPAEditorPage.xaml", "Coding/Pages/MQBFPAEditorPage.xaml", typeof(MQBFPAEditorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.MQBTailGatePageCustomization.xaml", "Coding/Pages/MQBTailGatePageCustomization.xaml", typeof(MQBTailGatePageCustomization))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.ToyotaTPMS2APage.xaml", "Coding/Pages/ToyotaTPMS2APage.xaml", typeof(ToyotaTPMS2APage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.TPMS4WheelsPage.xaml", "Coding/Pages/TPMS4WheelsPage.xaml", typeof(TPMS4WheelsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.VagRKDSPage.xaml", "Coding/Pages/VagRKDSPage.xaml", typeof(VagRKDSPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.ActionItem.xaml", "Dashboard/DashboardGauges/ActionItem.xaml", typeof(ActionItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.ChartItem.xaml", "Dashboard/DashboardGauges/ChartItem.xaml", typeof(ChartItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.CircularProgressItem.xaml", "Dashboard/DashboardGauges/CircularProgressItem.xaml", typeof(CircularProgressItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.GaugeBackground.xaml", "Dashboard/DashboardGauges/GaugeBackground.xaml", typeof(GaugeBackground))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.GaugeItem.xaml", "Dashboard/DashboardGauges/GaugeItem.xaml", typeof(GaugeItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.GaugeItemVar2.xaml", "Dashboard/DashboardGauges/GaugeItemVar2.xaml", typeof(GaugeItemVar2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.GaugeItemVar3.xaml", "Dashboard/DashboardGauges/GaugeItemVar3.xaml", typeof(GaugeItemVar3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.IndicatorItem.xaml", "Dashboard/DashboardGauges/IndicatorItem.xaml", typeof(IndicatorItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.LinearProgressItem.xaml", "Dashboard/DashboardGauges/LinearProgressItem.xaml", typeof(LinearProgressItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.LinearProgressItemiOS.xaml", "Dashboard/DashboardGauges/LinearProgressItemiOS.xaml", typeof(LinearProgressItemiOS))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.MultiChartItem.xaml", "Dashboard/DashboardGauges/MultiChartItem.xaml", typeof(MultiChartItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.MultiPidBarChart.xaml", "Dashboard/DashboardGauges/MultiPidBarChart.xaml", typeof(MultiPidBarChart))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.SimpleTextItem.xaml", "Dashboard/DashboardGauges/SimpleTextItem.xaml", typeof(SimpleTextItem))]
[assembly: XamlResourceId("CarScannerXamarinForms.Dashboard.DashboardGauges.TextItemHorizontal.xaml", "Dashboard/DashboardGauges/TextItemHorizontal.xaml", typeof(TextItemHorizontal))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecorderDTCPage.xaml", "DataRecorder/DataRecorderDTCPage.xaml", typeof(DataRecorderDTCPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecorderSettingsPage.xaml", "DataRecorder/DataRecorderSettingsPage.xaml", typeof(DataRecorderSettingsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecorderSingleChartViewerPage.xaml", "DataRecorder/DataRecorderSingleChartViewerPage.xaml", typeof(DataRecorderSingleChartViewerPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecorderSpeedTestPage.xaml", "DataRecorder/DataRecorderSpeedTestPage.xaml", typeof(DataRecorderSpeedTestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecorderViewerPage.xaml", "DataRecorder/DataRecorderViewerPage.xaml", typeof(DataRecorderViewerPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.DataRecordUC.xaml", "DataRecorder/DataRecordUC.xaml", typeof(DataRecordUC))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.MapForOneRecord.xaml", "DataRecorder/MapForOneRecord.xaml", typeof(MapForOneRecord))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.MapWithMultiChartV2.xaml", "DataRecorder/MapWithMultiChartV2.xaml", typeof(MapWithMultiChartV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.DataRecorder.TestPage.xaml", "DataRecorder/TestPage.xaml", typeof(global::CarScannerXamarinForms.DataRecorder.TestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DriveCycles.DriveCyclesListPage.xaml", "DriveCycles/DriveCyclesListPage.xaml", typeof(DriveCyclesListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DriveCycles.FuelStatisticsDatePeriodSelectorPage.xaml", "DriveCycles/FuelStatisticsDatePeriodSelectorPage.xaml", typeof(FuelStatisticsDatePeriodSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DriveCycles.FuelStatisticsPage.xaml", "DriveCycles/FuelStatisticsPage.xaml", typeof(FuelStatisticsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DTCv2.DTCv2Page.xaml", "DTCv2/DTCv2Page.xaml", typeof(DTCv2Page))]
[assembly: XamlResourceId("CarScannerXamarinForms.DTCv2.DTCv3Page.xaml", "DTCv2/DTCv3Page.xaml", typeof(DTCv3Page))]
[assembly: XamlResourceId("CarScannerXamarinForms.DTC.DTCWizardResultsPage.xaml", "DTC/DTCWizardResultsPage.xaml", typeof(DTCWizardResultsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DTC.DTCWizardSetupPage.xaml", "DTC/DTCWizardSetupPage.xaml", typeof(DTCWizardSetupPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.DTC.DTCWizardStartPage.xaml", "DTC/DTCWizardStartPage.xaml", typeof(DTCWizardStartPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.InApp.InAppPurchasePage.xaml", "InApp/InAppPurchasePage.xaml", typeof(InAppPurchasePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.InApp.InAppPurchasePageRUS.xaml", "InApp/InAppPurchasePageRUS.xaml", typeof(InAppPurchasePageRUS))]
[assembly: XamlResourceId("CarScannerXamarinForms.InApp.InAppPurchasePageV2.xaml", "InApp/InAppPurchasePageV2.xaml", typeof(InAppPurchasePageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.CollectDataPage.xaml", "Pages/CollectDataPage.xaml", typeof(CollectDataPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.ColorSelectorPageV2.xaml", "Pages/ColorSelectorPageV2.xaml", typeof(ColorSelectorPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.CustomAlertPage.xaml", "Pages/CustomAlertPage.xaml", typeof(CustomAlertPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardEditorPage.xaml", "Pages/Dashboard/DashboardEditorPage.xaml", typeof(DashboardEditorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardItemAdderPage.xaml", "Pages/Dashboard/DashboardItemAdderPage.xaml", typeof(DashboardItemAdderPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardItemAdderPageV2.xaml", "Pages/Dashboard/DashboardItemAdderPageV2.xaml", typeof(DashboardItemAdderPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardItemEditorV3.xaml", "Pages/Dashboard/DashboardItemEditorV3.xaml", typeof(DashboardItemEditorV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardItemTypeSelector.xaml", "Pages/Dashboard/DashboardItemTypeSelector.xaml", typeof(DashboardItemTypeSelector))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardMultiPidSelector.xaml", "Pages/Dashboard/DashboardMultiPidSelector.xaml", typeof(DashboardMultiPidSelector))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardPageAdder.xaml", "Pages/Dashboard/DashboardPageAdder.xaml", typeof(DashboardPageAdder))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardPageTemplateEditor.xaml", "Pages/Dashboard/DashboardPageTemplateEditor.xaml", typeof(DashboardPageTemplateEditor))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardXamlPage.xaml", "Pages/Dashboard/DashboardXamlPage.xaml", typeof(DashboardXamlPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.LiveDataMultiChartSelectorPageV3.xaml", "Pages/Dashboard/LiveDataMultiChartSelectorPageV3.xaml", typeof(LiveDataMultiChartSelectorPageV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.DebugPage.xaml", "Pages/DebugPage.xaml", typeof(DebugPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.DroidPermissionRequestPage.xaml", "Pages/DroidPermissionRequestPage.xaml", typeof(DroidPermissionRequestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.EcoTestPage.xaml", "Pages/EcoTestPage.xaml", typeof(EcoTestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.EcoTestPageV2.xaml", "Pages/EcoTestPageV2.xaml", typeof(EcoTestPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.EcuInfoPageV2.xaml", "Pages/EcuInfoPageV2.xaml", typeof(EcuInfoPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.FreezeFramePage.xaml", "Pages/FreezeFramePage.xaml", typeof(FreezeFramePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.ItemWithValueSelectorPage.xaml", "Pages/ItemWithValueSelectorPage.xaml", typeof(ItemWithValueSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LanguageSelectorPage.xaml", "Pages/LanguageSelectorPage.xaml", typeof(LanguageSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LanguageSelectorPageV2.xaml", "Pages/LanguageSelectorPageV2.xaml", typeof(LanguageSelectorPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LiveDataChartPage.xaml", "Pages/LiveDataChartPage.xaml", typeof(LiveDataChartPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LiveDataListPage.xaml", "Pages/LiveDataListPage.xaml", typeof(LiveDataListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LiveDataMultiChartPageV2.xaml", "Pages/LiveDataMultiChartPageV2.xaml", typeof(LiveDataMultiChartPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LiveDataMultiChartSelector.xaml", "Pages/LiveDataMultiChartSelector.xaml", typeof(LiveDataMultiChartSelector))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.LiveMultiChartPage.xaml", "Pages/LiveMultiChartPage.xaml", typeof(LiveMultiChartPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Mode06Page.xaml", "Pages/Mode06Page.xaml", typeof(Mode06Page))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.PerformanceTracking.xaml", "Pages/PerformanceTracking.xaml", typeof(PerformanceTracking))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.PIDSelectorV2.xaml", "Pages/PIDSelectorV2.xaml", typeof(PIDSelectorV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.PIDSelectorV3.xaml", "Pages/PIDSelectorV3.xaml", typeof(PIDSelectorV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.PopupInfoPage.xaml", "Pages/PopupInfoPage.xaml", typeof(PopupInfoPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.SimpleMainPage.xaml", "Pages/SimpleMainPage.xaml", typeof(SimpleMainPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.SpeedTestAdder.xaml", "Pages/SpeedTestAdder.xaml", typeof(SpeedTestAdder))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.SpeedTestPage.xaml", "Pages/SpeedTestPage.xaml", typeof(SpeedTestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.SpeedTestPageV2.xaml", "Pages/SpeedTestPageV2.xaml", typeof(SpeedTestPageV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.TerminalPage.xaml", "Pages/TerminalPage.xaml", typeof(TerminalPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.TestPage.xaml", "Pages/TestPage.xaml", typeof(global::CarScannerXamarinForms.TestPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.WelcomePage1V4.xaml", "Pages/WelcomePage1V4.xaml", typeof(WelcomePage1V4))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.WelcomePage2V3.xaml", "Pages/WelcomePage2V3.xaml", typeof(WelcomePage2V3))]
[assembly: XamlResourceId("CarScannerXamarinForms.PIDScanner.PIDScannerPage.xaml", "PIDScanner/PIDScannerPage.xaml", typeof(PIDScannerPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.ProfilesV2.ProfilesUpdatePage.xaml", "ProfilesV2/ProfilesUpdatePage.xaml", typeof(ProfilesUpdatePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.BTDeviceSelectorPage.xaml", "Settings/BTDeviceSelectorPage.xaml", typeof(BTDeviceSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.BTLEDeviceSelectorPage.xaml", "Settings/BTLEDeviceSelectorPage.xaml", typeof(BTLEDeviceSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.ContactDeveloperPage.xaml", "Settings/ContactDeveloperPage.xaml", typeof(ContactDeveloperPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.CustomCodingEditor.xaml", "Settings/CustomCodingEditor.xaml", typeof(CustomCodingEditor))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.CustomPIDsEditorPage.xaml", "Settings/CustomPIDsEditorPage.xaml", typeof(CustomPIDsEditorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.CustomPIDsListPage.xaml", "Settings/CustomPIDsListPage.xaml", typeof(CustomPIDsListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.ELMFailPage.xaml", "Settings/ELMFailPage.xaml", typeof(ELMFailPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.InfoPage.xaml", "Settings/InfoPage.xaml", typeof(InfoPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.InitSequenceEditorPage.xaml", "Settings/InitSequenceEditorPage.xaml", typeof(InitSequenceEditorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.MainPageConfigurationScreen.xaml", "Settings/MainPageConfigurationScreen.xaml", typeof(MainPageConfigurationScreen))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.ProfileSelectorV2Page.xaml", "Settings/ProfileSelectorV2Page.xaml", typeof(ProfileSelectorV2Page))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.ProfileSelectorV3.xaml", "Settings/ProfileSelectorV3.xaml", typeof(ProfileSelectorV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsBackup.xaml", "Settings/SettingsBackup.xaml", typeof(SettingsBackup))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsCustomCodingsListPage.xaml", "Settings/SettingsCustomCodingsListPage.xaml", typeof(SettingsCustomCodingsListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsDisabledPids.xaml", "Settings/SettingsDisabledPids.xaml", typeof(SettingsDisabledPids))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsFuelCalibrationPage.xaml", "Settings/SettingsFuelCalibrationPage.xaml", typeof(SettingsFuelCalibrationPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsGarage.xaml", "Settings/SettingsGarage.xaml", typeof(SettingsGarage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsGarageCarEditorPage.xaml", "Settings/SettingsGarageCarEditorPage.xaml", typeof(SettingsGarageCarEditorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsOptimizations.xaml", "Settings/SettingsOptimizations.xaml", typeof(SettingsOptimizations))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsPIDOverrideListPage.xaml", "Settings/SettingsPIDOverrideListPage.xaml", typeof(SettingsPIDOverrideListPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsRecording.xaml", "Settings/SettingsRecording.xaml", typeof(SettingsRecording))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsRecordRename.xaml", "Settings/SettingsRecordRename.xaml", typeof(SettingsRecordRename))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsConnectionExpertV3.xaml", "Settings/SettingsV3/SettingsConnectionExpertV3.xaml", typeof(SettingsConnectionExpertV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsConnectionPageV3.xaml", "Settings/SettingsV3/SettingsConnectionPageV3.xaml", typeof(SettingsConnectionPageV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsDashboardV3.xaml", "Settings/SettingsV3/SettingsDashboardV3.xaml", typeof(SettingsDashboardV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsFuelRateV3.xaml", "Settings/SettingsV3/SettingsFuelRateV3.xaml", typeof(SettingsFuelRateV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsInfoV3.xaml", "Settings/SettingsV3/SettingsInfoV3.xaml", typeof(SettingsInfoV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsInterfacePageV3.xaml", "Settings/SettingsV3/SettingsInterfacePageV3.xaml", typeof(SettingsInterfacePageV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsPIDOverrideEditorPageV3.xaml", "Settings/SettingsV3/SettingsPIDOverrideEditorPageV3.xaml", typeof(SettingsPIDOverrideEditorPageV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsRoot.xaml", "Settings/SettingsV3/SettingsRoot.xaml", typeof(SettingsRoot))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsUnitsV3.xaml", "Settings/SettingsV3/SettingsUnitsV3.xaml", typeof(SettingsUnitsV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.SettingsVehicleOptionsPageV3.xaml", "Settings/SettingsV3/SettingsVehicleOptionsPageV3.xaml", typeof(SettingsVehicleOptionsPageV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsV3.__SettingsCustomPIDEditorV3.xaml", "Settings/SettingsV3/__SettingsCustomPIDEditorV3.xaml", typeof(SettingsCustomPIDEditorV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Styles.DarkTheme.xaml", "Styles/DarkTheme.xaml", typeof(DarkTheme))]
[assembly: XamlResourceId("CarScannerXamarinForms.Styles.FontSizeCollection_Android.xaml", "Styles/FontSizeCollection_Android.xaml", typeof(FontSizeCollection_Android))]
[assembly: XamlResourceId("CarScannerXamarinForms.Styles.FontSizeCollection_iOS.xaml", "Styles/FontSizeCollection_iOS.xaml", typeof(FontSizeCollection_iOS))]
[assembly: XamlResourceId("CarScannerXamarinForms.Styles.LightTheme.xaml", "Styles/LightTheme.xaml", typeof(LightTheme))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.ActivityFrame.xaml", "UserControls/ActivityFrame.xaml", typeof(ActivityFrame))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.CheckBoxWithLabel.xaml", "UserControls/CheckBoxWithLabel.xaml", typeof(CheckBoxWithLabel))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.CheckSwitch.xaml", "UserControls/CheckSwitch.xaml", typeof(CheckSwitch))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.ColorMixer.ColorPickerEntry.xaml", "UserControls/ColorMixer/ColorPickerEntry.xaml", typeof(ColorPickerEntry))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.ColorMixer.ColorPickerMixer.xaml", "UserControls/ColorMixer/ColorPickerMixer.xaml", typeof(ColorPickerMixer))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.ColorSelectorPage.xaml", "UserControls/ColorSelectorPage.xaml", typeof(ColorSelectorPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.ComplexAdView.xaml", "UserControls/ComplexAdView.xaml", typeof(ComplexAdView))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.DashboardItemColorBox.xaml", "UserControls/DashboardItemColorBox.xaml", typeof(DashboardItemColorBox))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.LabelSwitch.xaml", "UserControls/LabelSwitch.xaml", typeof(LabelSwitch))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.LabelWithBorder.xaml", "UserControls/LabelWithBorder.xaml", typeof(LabelWithBorder))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.LiveDataChartUC.xaml", "UserControls/LiveDataChartUC.xaml", typeof(LiveDataChartUC))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.MainPageButton.xaml", "UserControls/MainPageButton.xaml", typeof(MainPageButton))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.NumericEntryV3.xaml", "UserControls/NumericEntryV3.xaml", typeof(NumericEntryV3))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.PermissionsRequestControl.xaml", "UserControls/PermissionsRequestControl.xaml", typeof(PermissionsRequestControl))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.SettingsCellWithPicker.xaml", "UserControls/SettingsCellWithPicker.xaml", typeof(SettingsCellWithPicker))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.SettingsCellWithPickerInCenter.xaml", "UserControls/SettingsCellWithPickerInCenter.xaml", typeof(SettingsCellWithPickerInCenter))]
[assembly: XamlResourceId("CarScannerXamarinForms.UserControls.SliderColorSelector.xaml", "UserControls/SliderColorSelector.xaml", typeof(SliderColorSelector))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.CodingModeSelection.xaml", "Coding/Pages/CodingModeSelection.xaml", typeof(CodingModeSelection))]
[assembly: XamlResourceId("CarScannerXamarinForms.Coding.Pages.WelcomePage2.xaml", "Coding/Pages/WelcomePage2.xaml", typeof(WelcomePage2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.Dashboard.DashboardItemEditor.xaml", "Pages/Dashboard/DashboardItemEditor.xaml", typeof(DashboardItemEditor))]
[assembly: XamlResourceId("CarScannerXamarinForms.Pages.WelcomePage1V3.xaml", "Pages/WelcomePage1V3.xaml", typeof(WelcomePage1V3))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.ProfileSelectorV2.xaml", "Settings/ProfileSelectorV2.xaml", typeof(ProfileSelectorV2))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsConnectionExpertPage.xaml", "Settings/SettingsConnectionExpertPage.xaml", typeof(SettingsConnectionExpertPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsConnectionPage.xaml", "Settings/SettingsConnectionPage.xaml", typeof(SettingsConnectionPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsDashboard.xaml", "Settings/SettingsDashboard.xaml", typeof(SettingsDashboard))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsFuelRatePage.xaml", "Settings/SettingsFuelRatePage.xaml", typeof(SettingsFuelRatePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsInterfacePage.xaml", "Settings/SettingsInterfacePage.xaml", typeof(SettingsInterfacePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsPage.xaml", "Settings/SettingsPage.xaml", typeof(SettingsPage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsPIDOverridePage.xaml", "Settings/SettingsPIDOverridePage.xaml", typeof(SettingsPIDOverridePage))]
[assembly: XamlResourceId("CarScannerXamarinForms.Settings.SettingsVehicleOptions.xaml", "Settings/SettingsVehicleOptions.xaml", typeof(SettingsVehicleOptions))]
[assembly: AssemblyCompany("CarScannerXamarinForms")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("CarScannerXamarinForms")]
[assembly: AssemblyTitle("CarScannerXamarinForms")]
