<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- 使用本地的 dnlib -->
    <Reference Include="dnlib">
      <HintPath>../DllPatcher/bin/Release/net10.0/dnlib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
